### ISSUE TITLE
selectivity_select does not follow standard select helper

### ISSUE THREAD

**Issue by pusewicz** [msx2/selectivity-rails#6]
``` ruby
selectivity_select 'Mustang', from: 'Model'
```

does not work, whereas standard 

``` ruby
select 'Mustang', from: 'Model'
```

does! :smile:

It would be great if the selectivity RSpec helper followed the standard one in terms of what it accepts in the `from:` param.

**Comment by msx2** [comment]
Yes, I agree. It would be extremely more convenient to use labels and not being limited to style attributes only. Will definitely work on this in the near future! :)

**Comment by msx2** [comment]
@pusewicz This is done in #9. I'm neither proud nor happy with this solution and will probably refactor this soon, but for time being it's sufficient ;)
